# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23.1'

    - name: Build
      run: |
        GOOS=windows GOARCH=amd64 go build -o shortcut.exe ./main.go

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        path: ./shorcut.exe
